inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false # default: true

Style/BlockDelimiters:
  Enabled: false # default: true

Style/Documentation:
  Enabled: false # default: true

Style/MethodCallWithArgsParentheses:
  inherit_mode:
    merge:
      - IgnoredMethods
  IgnoredMethods:
    # rspec
    - after
    - and
    - around
    - before
    - context
    - describe
    - include_context
    - include_example
    - include_examples
    - it
    - it_behaves_like
    - not_to
    - or
    - shared_context
    - shared_examples
    - shared_examples_for
    - specify
    - to
    - to_not
